### ISSUE TITLE
ERROR:uvicorn.error:Error loading ASGI app. Attribute "app" not found in module "app".

### ISSUE THREAD

**Issue by gandolfi974** [lazarusking/gradio-ffmpeg#1]
hi,
i have installed the app in windows with venv python. i have this error.
ERROR:uvicorn.error:Error loading ASGI app. Attribute "app" not found in module "app".

thanks for your help

**Comment by lazarusking** [comment]
I may upgrade this to the new gradio version soon
Try using `python app.py` to run it instead

**Comment by lazarusking** [comment]
I've done the upgrade to gradio 5, I think it should work now.
Tested on python 3.11
